### ISSUE TITLE
docker-compose up -d后报错

### ISSUE THREAD

**Issue by StevenKSaint** [tdragon6/Supershell#1]
root@asdasd:/home/Supershell# docker-compose up -d
/snap/docker/2746/lib/python3.6/site-packages/paramiko/transport.py:32: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography (40.0) will be the last to support Python 3.6.
  from cryptography.hazmat.backends import default_backend
Building flask
error checking context: 'no permission to read from '/home/Supershell/.DS_Store''.
ERROR: Service 'flask' failed to build : Build failed

给.DS_Store chmod 777还是不行

**Comment by tdragon6** [comment]
Hi，`.DS_Store` 文件是darwin系统产生的目录文件

请问你是否先在mac电脑上下载了源码，解压后再放到vps上执行的呢？

如果是的话请重新在vps上直接下载源码解压后执行即可。

**Comment by StevenKSaint** [comment]
谢谢兄弟，是这个情况，没想到多了这个文件，竟然执行不成功，以为程序不会调用该文件的，删除后，解决了。

**Comment by tdragon6** [comment]
还有我注意到你上面构建时的提示python3,6，但是flask的dockerfile中应该是python3.8，我不确定这对后续是否有影响，如果再碰到问题，欢迎开新的issue，现关闭这个issue。
