### ISSUE TITLE
大文件无法下载

### ISSUE THREAD

**Issue by ffsfwnuiaww** [tdragon6/Supershell#10]
..140m左右的文件无法下载 网页直接报错了,,,然后我分卷压缩10m 10m的去下载了

**Comment by tdragon6** [comment]
Hi，

1. 浏览器报错的信息是什么
2. 是否方便附上日志
3. 该主机是否掉线重连。目前上传下载功能不稳定，长时间的连接传输可能导致掉线重连。

**Comment by ffsfwnuiaww** [comment]
```
http://xxxxx:xxx/supershell/session/files/download?path=%2Ftmp%2Fxxxxxxx.zip&sessid=xxxx
```


直接就502了

主机没有重连 很稳定,   测试了一下小文件 秒下载

**Comment by tdragon6** [comment]
业务和gunicorn日志能看到什么报错信息吗

**Comment by ffsfwnuiaww** [comment]
<img width="757" alt="image" src="https://user-images.githubusercontent.com/89639412/230907099-97e658e4-0969-4bc1-8cfc-7126dda8be47.png">

**Comment by ffsfwnuiaww** [comment]
<img width="968" alt="image" src="https://user-images.githubusercontent.com/89639412/230907169-ff557942-ad46-4ba6-b5aa-6222328f748f.png">

**Comment by ffsfwnuiaww** [comment]
老哥 你要不参考一下隔壁牛屎花 的代码吧,

**Comment by ffsfwnuiaww** [comment]
先把目标下载到 服务器本地。 然后用户再从服务器下载

**Comment by tdragon6** [comment]
之前考虑过这种形式，但是感觉中转多余了就摒弃了，可以通过本地使用sftp命令更稳定快捷地下载文件，参阅[Sftp传输](https://github.com/tdragon6/Supershell/wiki/Sftp%E4%BC%A0%E8%BE%93)

回头我复现一下，如果无法解决，会考虑使用服务器作中转。

**Comment by ffsfwnuiaww** [comment]
对了 要是你更新了新的代码 我把之前的程序关了 替换成新的程序。 那我之前上线的机子 还能继续上线么?

**Comment by tdragon6** [comment]
可以的，新代码目录替换原本的volume就行了

**Comment by tdragon6** [comment]
参见v2.0.0版本

建议使用私钥原生sftp下载文件

https://github.com/tdragon6/Supershell/releases/tag/v2.0.0
