### ISSUE TITLE
关于资产分类的更好想法建议

### ISSUE THREAD

**Issue by ffsfwnuiaww** [tdragon6/Supershell#12]
<img width="239" alt="image" src="https://user-images.githubusercontent.com/89639412/231351072-bb058c9c-2871-4a11-9c89-58935b294124.png">

类似于蚁剑这样。可以任意分组  根据不同资产 划分到任意分组里。 并且有侧方显示该分组有多少个资产

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/89639412/231351353-c10d30f0-d6fd-4544-9d61-5796c957574d.png">

还有就是一直掉线的问题,,,,掉线后 能否根据内网ip 以及hotname    把之前的备注 重新恢复

**Comment by tdragon6** [comment]
筛选目前基本满足分组查看，优先解决掉线和校准类的优化问题。

**Comment by ffsfwnuiaww** [comment]
没事了 当我没说。 才看到原来可以 筛选分组,,,,,,,,,那就解决一下掉线优化问题进行了
