### ISSUE TITLE
镜像构建不了

### ISSUE THREAD

**Issue by 1T0day** [tdragon6/Supershell#15]
ERROR: https://mirrors.ustc.edu.cn/alpine/v3.17/main: temporary error (try again later)
WARNING: Ignoring https://mirrors.ustc.edu.cn/alpine/v3.17/main: No such file or directory
ERROR: https://mirrors.ustc.edu.cn/alpine/v3.17/community: temporary error (try again later)
WARNING: Ignoring https://mirrors.ustc.edu.cn/alpine/v3.17/community: No such file or directory
2 errors; 37 distinct packages available
ERROR: Service 'flask' failed to build: The command '/bin/sh -c sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories &&     apk update &&     apk -U --no-cache add gcc python3-dev libc-dev libffi-

**Comment by 1T0day** [comment]
抱歉，通过查看资料，有位大佬给出了解决方案，原来是docker的dns请求的问题，附链接https://github.com/ustclug/discussions/issues/166

**Comment by tdragon6** [comment]
参见v2.0.0版本

支持通过云仓库拉取镜像

https://github.com/tdragon6/Supershell/releases/tag/v2.0.0
