### ISSUE TITLE
使用心得

### ISSUE THREAD

**Issue by Vipersec1** [tdragon6/Supershell#17]
你好作者，非常感谢提供如此优秀的C2，在经过一次实战中，我发现了一些问题，如果Supershell的特征被检测到，我们只能放弃这个C2平台，因为不可以生成Payload，类似CS中 Payload Gen中所实现的那样，是否可以支持一下生成payload，或者将payload代码进行公开（当然，您开发不容易，理解万岁）。我的想法是这样，如果公开或者说可以生成Payload，我们可以将这个C2平台用起来非常的得心应手。

再次给作者您点赞

**Comment by Emmp7y** [comment]
https://github.com/NHAS/reverse_ssh/releases/tag/v1.0.17

从这里看不就完了，
