### ISSUE TITLE
几个功能优化建议

### ISSUE THREAD

**Issue by xiaoyiddos** [tdragon6/Supershell#18]
1. 能把备注放于前端显示,不然要每个手动点开才看的到备注
2. 支持每页显示数量自定义
3. 支持批量选择主机进行断开或者删除操作

**Comment by tdragon6** [comment]
参见v2.0.0版本

备注本意为较长的文本，放在前端影响显示，如果是短小的标志，可以放在分组里

https://github.com/tdragon6/Supershell/releases/tag/v2.0.0
