### ISSUE TITLE
docker无法构建

### ISSUE THREAD

**Issue by AuFeng111** [tdragon6/Supershell#19]
Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
Get:4 http://deb.debian.org/debian bullseye/main amd64 Packages [8183 kB] 
卡在这个步骤了

**Comment by pengtao007** [comment]
翻墙下载可以解决这个问题，你找个机场，用软路由全局翻后下载。

**Comment by tdragon6** [comment]
参见v2.0.0版本

现支持从云仓库拉取镜像，对于国内主机只需配置docker源

https://github.com/tdragon6/Supershell/releases/tag/v2.0.0
