### ISSUE TITLE
Kali中docker-compose构建失败

### ISSUE THREAD

**Issue by qahehe** [tdragon6/Supershell#20]
![image](https://user-images.githubusercontent.com/25258443/234047604-9cd051fa-f35a-424d-bca8-c31e8a66a12f.png)
如图是kali2022.2版本，python是默认的版本3.10.6，docker-compose也是apt命令行安装，是什么原因呢

**Comment by pcgoodboy** [comment]
我的也是

**Comment by pcgoodboy** [comment]
不过我在rssh哪里凉的，原因是用了apt命令，编辑dockerfile，改成apt-get就可以了

**Comment by tdragon6** [comment]
参见v2.0.0版本

现支持从云仓库拉取镜像

https://github.com/tdragon6/Supershell/releases/tag/v2.0.0
