### ISSUE TITLE
登录成功后，重定向请求过多。

### ISSUE THREAD

**Issue by hututudehutu** [tdragon6/Supershell#21]
![image](https://user-images.githubusercontent.com/64538312/234746786-d404d798-478c-4a7b-8274-d05430c518ef.png)

**Comment by heiheip** [comment]
我也遇到了如何解决

**Comment by heiheip** [comment]
抓包发现是因为请求不带cookie所以导致一直跳转， 搞个插件自己带上cookie就行了

**Comment by skyz233** [comment]
> 兄弟已经解决了吗？

**Comment by tdragon6** [comment]
看看v2.0.0还存在这个问题吗，我检查代码后没有发现逻辑的问题，尝试清空cookie或设置其他值再刷新访问

https://github.com/tdragon6/Supershell/releases/tag/v2.0.0
