### ISSUE TITLE
交互终端异常

### ISSUE THREAD

**Issue by pcgoodboy** [tdragon6/Supershell#23]
我用谷歌浏览器了，火狐会闪动，报错
Warning: Permanently added '[rssh]:3232' (ED25519) to the list of known hosts.
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0770 for '/root/.ssh/id_rsa' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "/root/.ssh/id_rsa": bad permissions
root@rssh: Permission denied (publickey).
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535
求解

**Comment by tdragon6** [comment]
参见v2.0.0版本

对于下载到本地的私钥，请赋予600权限

https://github.com/tdragon6/Supershell/releases/tag/v2.0.0
