### ISSUE TITLE
supershell存在xss，可获取管理员cookie

### ISSUE THREAD

**Issue by condesings** [tdragon6/Supershell#24]
webhook.py下面的get_target_user  函数，调用 exec_command 执行 DOS 语句获取 whoami，接受值没有任何过滤存在xss，可以通过修改用户名造成xss获取supershell的管理员cookie

**Comment by tdragon6** [comment]
参见v2.0.0版本

https://github.com/tdragon6/Supershell/releases/tag/v2.0.0
