### ISSUE TITLE
ERROR [rssh 3/8]

### ISSUE THREAD

**Issue by mwuhang** [tdragon6/Supershell#25]
ERROR [rssh 3/8] RUN sed -i s@/archive.ubuntu.com/@/mirrors.aliyun.com/@g /etc/apt/sources.list &&     go env -w GOPROXY=
这个是什么问题，我该怎么做

**Comment by mwuhang** [comment]
麻烦大家了

**Comment by tdragon6** [comment]
参见v2.0.0版本

现支持从云仓库拉取镜像

https://github.com/tdragon6/Supershell/releases/tag/v2.0.0
