### ISSUE TITLE
浏览文件处，存在xss

### ISSUE THREAD

**Issue by RuoJi6** [tdragon6/Supershell#28]
![image](https://github.com/tdragon6/Supershell/assets/79234113/6cf490f5-8dce-4476-bd4d-836ece3d97dc)
![image](https://github.com/tdragon6/Supershell/assets/79234113/be9922dc-c1e7-4bed-a80c-4c9cdb3b53f1)
![image](https://github.com/tdragon6/Supershell/assets/79234113/6aad3c4c-1f7e-46f7-8d26-c7d194f5b4d1)
![image](https://github.com/tdragon6/Supershell/assets/79234113/75e66515-e309-4d1f-9d92-1cf4de052ca9)

**Comment by tdragon6** [comment]
参见v2.0.0版本

https://github.com/tdragon6/Supershell/releases/tag/v2.0.0
