### ISSUE TITLE
终端交互报错 

### ISSUE THREAD

**Issue by hsbugs** [tdragon6/Supershell#3]
![image](https://user-images.githubusercontent.com/30823569/230086733-e6e013eb-c364-4b1a-abf7-28f56aa6c1f3.png)

**Comment by tdragon6** [comment]
Hi，请问密钥是不是从外部拷贝至 `./volume/flask/key/id_rsa`，此问题是由于密钥权限过大导致的ssh安全拦截。

### 临时解决方案：

在Supershell目录下

1. 进入shell容器 `docker-compose exec shell /bin/sh`
2. 降低密钥权限 `chmod 600 /root/.ssh/id_rsa`
3. 进入memfd容器 `docker-compose exec memfd /bin/sh`
4. 降低密钥权限 `chmod 600 /root/.ssh/id_rsa`

看看是否可以正常获取Shell

**Comment by tdragon6** [comment]
容器启动前确保 `./volume/flask/key/id_rsa` 的权限为600

**Comment by tdragon6** [comment]
目标主机windows重启后进程关闭，如果有管理员权限可以尝试安装服务。

如果安装服务失败目前只能自行想办法将exe payload设置开机自启。

**Comment by hsbugs** [comment]
thanks

**Comment by tdragon6** [comment]
欢迎有其他问题开新的issue，现关闭此issue
