### ISSUE TITLE
Docker-compose up error: https://mirrors.ustc.edu.cn/alpine/v3.18/community: Permission denied

### ISSUE THREAD

**Issue by ss256100** [tdragon6/Supershell#30]
docker-compose up log below:

❯ docker-compose up                                                                             
[+] Running 13/13
 ✔ redis 6 layers [⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                                  5.5s 
   ✔ c9b1b535fdd9 Pull complete                                                                                    1.2s 
   ✔ 8dd5e7a0ba4a Pull complete                                                                                    1.4s 
   ✔ e20c1cdf5aef Pull complete                                                                                    2.4s 
   ✔ f06a0c1e566e Pull complete                                                                                    3.1s 
   ✔ 230b5c8df708 Pull complete                                                                                    3.2s 
   ✔ 0cb9ac88f5bf Pull complete                                                                                    3.3s 
 ✔ nginx 5 layers [⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                                   4.9s 
   ✔ ddad3d7c1e96 Pull complete                                                                                    0.8s 
   ✔ c7974bc8b744 Pull complete                                                                                    2.5s 
   ✔ d04f0a2e9201 Pull complete                                                                                    2.6s 
   ✔ df7ae1cb4591 Pull complete                                                                                    2.8s 
   ✔ 4259d8811e1d Pull complete                                                                                    2.9s 
[+] Building 258.3s (8/8) FINISHED                                                                                      
 => [flask internal] load .dockerignore                                                                            0.7s
 => => transferring context: 2B                                                                                    0.0s
 => [flask internal] load build definition from Dockerfile.Flask                                                   0.6s
 => => transferring dockerfile: 353B                                                                               0.0s
 => [flask internal] load metadata for docker.io/library/python:3.8-alpine                                         6.7s
 => [flask 1/4] FROM docker.io/library/python:3.8-alpine@sha256:fca97c8ba04d829e53f6ed1990f39ff02a7bcc15fa4634594  6.4s
 => => resolve docker.io/library/python:3.8-alpine@sha256:fca97c8ba04d829e53f6ed1990f39ff02a7bcc15fa4634594608d78  0.4s
 => => sha256:fca97c8ba04d829e53f6ed1990f39ff02a7bcc15fa4634594608d78636b9c4d1 1.65kB / 1.65kB                     0.0s
 => => sha256:97d86d4a8723429a8f8240e9eb08062c257247a65edb0a70ea727733185c942f 1.37kB / 1.37kB                     0.0s
 => => sha256:34e19d928e8c3f05d67456a56359cf08e2c011d738194896bc3d8d3d25f3f688 6.30kB / 6.30kB                     0.0s
 => => sha256:31e352740f534f9ad170f75378a84fe453d6156e40700b882d737a8f4a6988a3 3.40MB / 3.40MB                     0.4s
 => => sha256:cfcc276e4459ecb909a4257fdf7647034eb3b2ab1f0d0c0bba54856c39079c50 622.30kB / 622.30kB                 0.4s
 => => sha256:bc685b93f82a3ac5e95536a2e757a789d640e279a5888f4c6007779ceae9851b 13.26MB / 13.26MB                   0.9s
 => => extracting sha256:31e352740f534f9ad170f75378a84fe453d6156e40700b882d737a8f4a6988a3                          0.4s
 => => sha256:77f0dfc57de13ffea5ce2a048bfbf9929c75d49dd34b4dedb9fa972cf7908def 2.85MB / 2.85MB                     1.2s
 => => sha256:12eb12cd52d020f9519467aaf5bac546fa19fb68be7ef8b9af701bf483e79bdc 241B / 241B                         1.0s
 => => extracting sha256:cfcc276e4459ecb909a4257fdf7647034eb3b2ab1f0d0c0bba54856c39079c50                          0.6s
 => => extracting sha256:bc685b93f82a3ac5e95536a2e757a789d640e279a5888f4c6007779ceae9851b                          1.4s
 => => extracting sha256:12eb12cd52d020f9519467aaf5bac546fa19fb68be7ef8b9af701bf483e79bdc                          0.0s
 => => extracting sha256:77f0dfc57de13ffea5ce2a048bfbf9929c75d49dd34b4dedb9fa972cf7908def                          0.6s
 => [flask internal] load build context                                                                            0.4s
 => => transferring context: 381.21kB                                                                              0.0s
 => [flask 2/4] WORKDIR /app                                                                                       1.2s
 => [flask 3/4] COPY ./flask .                                                                                     0.4s
 => ERROR [flask 4/4] RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories &&       242.4s
------                                                                                                                  
 > [flask 4/4] RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories &&     apk update &&     apk -U --no-cache add gcc python3-dev libc-dev libffi-dev &&     pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple:                                                                                                 
0.764 fetch https://mirrors.ustc.edu.cn/alpine/v3.18/main/x86_64/APKINDEX.tar.gz                                        
121.8 WARNING: updating and opening https://mirrors.ustc.edu.cn/alpine/v3.18/main: Permission denied
121.8 fetch https://mirrors.ustc.edu.cn/alpine/v3.18/community/x86_64/APKINDEX.tar.gz
242.2 WARNING: updating and opening https://mirrors.ustc.edu.cn/alpine/v3.18/community: Permission denied
242.2 4 unavailable, 0 stale; 38 distinct packages available
------
failed to solve: process "/bin/sh -c sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories &&

**Comment by tdragon6** [comment]
参见v2.0.0版本

现支持从云仓库拉取镜像

https://github.com/tdragon6/Supershell/releases/tag/v2.0.0
