### ISSUE TITLE
重复上线

### ISSUE THREAD

**Issue by websecer** [tdragon6/Supershell#34]
使用了半月，发现重复上线的问题好严重，目前都80个在线了而且不是每个会话都是有效的，只能一个一个的往后查，多半无效

**Comment by tdragon6** [comment]
在v2.0.0版本中看看这个问题缓解了么，同一主机执行一次回连客户端的话只会有一个会话在线，可能会断线重连，但数据校准后会保证只有一台在线

https://github.com/tdragon6/Supershell/releases/tag/v2.0.0
