### ISSUE TITLE
生成客户端问题

### ISSUE THREAD

**Issue by haiyou2233** [tdragon6/Supershell#38]
更新版本后，生成客户端选择系统构架和流量类型时没有下拉框。选择不了。

**Comment by haiyou2233** [comment]
Linux FSDDES9 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux本地环境。其他的功能都正常。

**Comment by tdragon6** [comment]
可以通过以下两点定位一下问题：

1、使用的浏览器是什么，如果不是chrome内核浏览器，可以尝试使用chrome浏览器试试还有这个问题吗
2、F12 看一下js有啥报错么

**Comment by haiyou2233** [comment]
> 可以通过以下两点定位一下问题：
> 
> 1、使用的浏览器是什么，如果不是chrome内核浏览器，可以尝试使用chrome浏览器试试还有这个问题吗 2、F12 看一下js有啥报错么

桌面两个chrome，换另外一个就好了。谢谢师傅的解答
