### ISSUE TITLE
docker部署报错：unknown flag: --iidfile

### ISSUE THREAD

**Issue by heikanet** [tdragon6/Supershell#4]
Building flask
unknown flag: --iidfile
See 'docker build --help'.
ERROR: Service 'flask' failed to build : Build failed

https://stackoverflow.com/questions/67010408/unable-to-start-docker-container-from-docker-compose-unknown-flag-iidfile

**Comment by tdragon6** [comment]
Hi，我测试和开发的docker-compose版本为 `1.25.0` ，网上查询此问题的结果基本都是以回退docker-compose版本的方式解决，没有找到相关的原因，不知道你是否通过回退docker-compose版本解决了这个问题。

后续我会找时间跟踪和研究docker-compose的这个版本问题，能兼容各种版本是最好了。

**Comment by tdragon6** [comment]
还有是否方便贴出你的docker version和docker-compose version

**Comment by tdragon6** [comment]
此issue作为问题查询参考，现关闭此issue
