### ISSUE TITLE
进程名称问题

### ISSUE THREAD

**Issue by Burden-xy** [tdragon6/Supershell#5]
能否自定义client的进程名称，目前默认是exe，很明显。

**Comment by tdragon6** [comment]
Hi，请问你是指win下payload执行后后台进程的名称吗，目前进程名跟着客户端名称走的，或许可以通过这几种方式隐藏：

1. 通过dll加载到其他进程中
2. 安装服务
3. 内存执行中再注入一遍payload

虽然2和3不一定会成功

**Comment by Burden-xy** [comment]
> Hi，请问你是指win下payload执行后后台进程的名称吗，目前进程名跟着客户端名称走的，或许可以通过这几种方式隐藏：
> 
>     1. 通过dll加载到其他进程中
> 
>     2. 安装服务
> 
>     3. 内存执行中再注入一遍payload
> 
> 
> 虽然2和3不一定会成功
linux下的进程名称
tcp        0      0 10.0.4.2:43574          X.X.X.X:3232      ESTABLISHED 17763/exe

**Comment by Burden-xy** [comment]
> Hi，请问你是指win下payload执行后后台进程的名称吗，目前进程名跟着客户端名称走的，或许可以通过这几种方式隐藏：
> 
>     1. 通过dll加载到其他进程中
> 
>     2. 安装服务
> 
>     3. 内存执行中再注入一遍payload
> 
> 
> 虽然2和3不一定会成功

指的是linux下的进程名称
tcp 0 0 10.0.4.2:43574 X.X.X.X:3232 ESTABLISHED 17763/exe

**Comment by skin-xp** [comment]
linux下会生成一个进程 /proc/self/exe --foreground

**Comment by tdragon6** [comment]
参见v2.0.0版本

https://github.com/tdragon6/Supershell/releases/tag/v2.0.0
