### ISSUE TITLE
arm64的kali build不起来

### ISSUE THREAD

**Issue by superboy-zjc** [tdragon6/Supershell#52]
你好，arm64的kali，build不起来，`docker logs` 会发现多个container都是报错`exec /bin/sh: exec format error`
<img width="1392" alt="image" src="https://github.com/tdragon6/Supershell/assets/60600792/e8fe5245-ff5a-4693-9765-9bfc3b6dc71f">
既然M芯片可以正常运行，按道理arm64的kali也可以正常运行。但我这边就是运行不起来。网上查了一下，貌似是几个image都是amd64架构的，比如这个image `tdragon6/supershell_flask:v2.0.0`，通过`sudo docker image inspect`可以看到是amd64的
<img width="1392" alt="image" src="https://github.com/tdragon6/Supershell/assets/60600792/83c9bdbc-af82-4dde-935d-b1855e41251b">。 请问作者有神么解决方案吗

**Comment by loach2020** [comment]
建议你换台amd64的设备

**Comment by superboy-zjc** [comment]
通过qemu Build起来了，一点不慢可以的。

**Comment by superboy-zjc** [comment]
> 建议你换台amd64的设备

建议你少建议
