### ISSUE TITLE
rssh/Dockerfile 换源错误

### ISSUE THREAD

**Issue by co0ontty** [tdragon6/Supershell#6]
应该替换换源命令为
sed -i s@/deb.debian.org/@/mirrors.aliyun.com/@g /etc/apt/sources.list

**Comment by tdragon6** [comment]
之前没注意，感谢纠正，下个版本会顺便修正

**Comment by co0ontty** [comment]
我创建一个 pr 吧

**Comment by carr0t2** [comment]
这个也错了  /var/cache/apk/

**Comment by pcgoodboy** [comment]
这个源有问题，不过我在服务器部署成功了，于是我把rssh的镜像复制到了kali

**Comment by tdragon6** [comment]
参见v2.0.0版本

https://github.com/tdragon6/Supershell/releases/tag/v2.0.0
