### ISSUE TITLE
新版本能增加一个支持cdn上线的功能么

### ISSUE THREAD

**Issue by ffsfwnuiaww** [tdragon6/Supershell#7]

**Comment by tdragon6** [comment]
Hi，请问你是想要通过cdn作中间解析隐藏IP，因此需要我在回连地址添加域名的支持吗？

**Comment by ffsfwnuiaww** [comment]
对。隐藏一下本机ip。要不然被发现 或者被拉黑 加入黑名单了  老是换ip 可不太行

**Comment by JFengLee** [comment]
同求回连地址支持域名

**Comment by tdragon6** [comment]
参见v2.0.0版本

https://github.com/tdragon6/Supershell/releases/tag/v2.0.0
