### ISSUE TITLE
测试发现几个功能性问题

### ISSUE THREAD

**Issue by StevenKSaint** [tdragon6/Supershell#9]
1.主机会频繁上线，一段时间后，就会生成很多的上线主机（同一个）。
2.在windows server 2019 x64系统执行64位客户端时，出现the system cannot execute the specified program。运行32位客户端，发现主机上线，仅仅是显示上线，其他功能都无法使用。执行交互终端报错channel 0:open failed:connect failed: no clients matched;stdio forwarding failed
3.关于进阶功能windows安装服务，会出现目标机器重启后，立马上线一台机器，但立马掉线的情况，但是查看目标机器发现服务进程还在。但就是无法再次上线。

**Comment by tdragon6** [comment]
还有日志能看出什么信息嘛，是否方便附上一些相关的日志

**Comment by StevenKSaint** [comment]
1.数据校准后，把离线的主机全部删除了，剩下在线主机，但是过段时间后，离线主机又会增加。必须每次数据校准，要不然客户端列表会越来越多。
2.生成的大小没有问题，上传上去也没问题，但是运行就会报错the system cannot execute the specified program，现在怀疑是被杀软拦截了（麦咖啡）然后马就没了。32位却没被杀，木马文件还在，但上线后，功能无效，数据校准后，直接删除了，应该是判断为离线了。
3.win11
日志看了下，没有什么有用信息。。。

**Comment by tdragon6** [comment]
我明白了，这可能比较麻烦，可能和连接的稳定性有关，需要花一些时间去排查，是否方便留下你的vx等联系方式，私下联系你

**Comment by StevenKSaint** [comment]
vx:wazex819

**Comment by ffsfwnuiaww** [comment]
遇到了同问题,,,,一次上线三四个 倒是没什么,,,, 就是假设你打内网的时候上线了4-5台机子了,,然后睡了一觉起来 发现莫名其妙全部都掉线了 又重新上线了。出口ip还都是同一个。根本无法区分 及其混乱.      之前的备注也全没了


感觉是连接稳定性的问题

**Comment by ffsfwnuiaww** [comment]
<img width="1540" alt="image" src="https://user-images.githubusercontent.com/89639412/231180028-9b760266-7410-4506-bacc-9b8ea9f4e0f7.png">

不如吧架构 这里 改成 主机名,,,,,  这样要是掉了的话。二次上线没有备注 可以通过主机名直观的看一下。   要不然还得点开一个一个看

**Comment by CloudStrifer** [comment]
> 1.主机会频繁上线，一段时间后，就会生成很多的上线主机（同一个）。 2.在windows server 2019 x64系统执行64位客户端时，出现the system cannot execute the specified program。运行32位客户端，发现主机上线，仅仅是显示上线，其他功能都无法使用。执行交互终端报错channel 0:open failed:connect failed: no clients matched;stdio forwarding failed 3.关于进阶功能windows安装服务，会出现目标机器重启后，立马上线一台机器，但立马掉线的情况，但是查看目标机器发现服务进程还在。但就是无法再次上线。

you are a dog

**Comment by tdragon6** [comment]
参见v2.0.0版本

主机名有时过长会影响前端显示，所以放在详细信息里

测试发现问题再提新issue哈

https://github.com/tdragon6/Supershell/releases/tag/v2.0.0
